### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by merolaika** [BB31420/AI-Auto-Video-Generator#5]
Hello there, i get this error when i write prompt

`Traceback (most recent call last):
  File "C:\ai\AI-Auto-Video-Generator\main.py", line 42, in <module>
    main()
  File "C:\ai\AI-Auto-Video-Generator\main.py", line 14, in main
    story, final_story_prompt = generate_story(story_prompt)  # Update the assignment to get the final_story_prompt
  File "C:\ai\AI-Auto-Video-Generator\story_generator.py", line 12, in generate_story
    response = openai.Completion.create(
  File "C:\Users\mero\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\mero\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\mero\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\mero\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\mero\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.`

i have credit open ai and elevenlabs

**Comment by BB31420** [comment]
Hi. Try creating a new open ai key and saving it in the .env file that contains these two lines of text. No need for " " or ( ). 

```
OPENAI_API_KEY = YOUR_API_KEY_HERE

ELEVENLABS_API_KEY = YOUR_API_KEY_HERE
```

**Comment by merolaika** [comment]
I did what you said but I'm having the same problem again.

`(base) C:\ai\AI-Auto-Video-Generator>py main.py "Create a haiku about nature"
Enter a story prompt: Create a haiku about nature
Traceback (most recent call last):
  File "C:\ai\AI-Auto-Video-Generator\main.py", line 42, in <module>
    main()
  File "C:\ai\AI-Auto-Video-Generator\main.py", line 14, in main
    story, final_story_prompt = generate_story(story_prompt)  # Update the assignment to get the final_story_prompt
  File "C:\ai\AI-Auto-Video-Generator\story_generator.py", line 12, in generate_story
    response = openai.Completion.create(
  File "C:\Users\mero\AppData\Roaming\Python\Python310\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\mero\AppData\Roaming\Python\Python310\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\mero\AppData\Roaming\Python\Python310\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\mero\AppData\Roaming\Python\Python310\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\mero\AppData\Roaming\Python\Python310\site-packages\openai\api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

(base) C:\ai\AI-Auto-Video-Generator>`
